version: "3"
services:
    app:
        build:
            context: .
        ports:
            - "80:80"
        volumes:
            - ./:/app
        command: >
          sh -c "wait-for-it db:5432 -- &&
                 alembic upgrade head &&
                 uvicorn src.main:app --host 0.0.0.0 --port 80 --reload"
        env_file:
            - .env
        depends_on:
            - db
        restart: always
    db:
        image: "postgres"
        container_name: db_service
        env_file:
            - .env
        ports:
            - "5433:5432"
        volumes:
            - db_data:/var/lib/postgresql/data/
        restart: always
    redis:
        image: redis
        container_name: redis_service
        ports:
            - "6379:6379"
        restart: always
    celery_worker:
        build:
            context: .
        container_name: celery_worker_service
        volumes:
            - ./:/app
        entrypoint: celery
        command:
            -A celery_config.app worker -l info
        env_file:
            - .env
        links:
            - redis
        depends_on:
            - redis
            - app
        restart: always
volumes:
    db_data:
        driver: local
