"""Created: Book, Author, Genre, BookAuthor

Revision ID: 54a64ee7a543
Revises: 
Create Date: 2023-12-21 16:06:22.246991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a64ee7a543'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors')),
    sa.UniqueConstraint('first_name', 'last_name', name='uq_authors_first_name_last_name')
    )
    op.create_index(op.f('ix_authors_first_name'), 'authors', ['first_name'], unique=False)
    op.create_index(op.f('ix_authors_last_name'), 'authors', ['last_name'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres'))
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('date_published', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_books_genre_id_genres'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=True)
    op.create_table('books_authors',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_books_authors_author_id_authors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_books_authors_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('author_id', 'book_id', name=op.f('pk_books_authors'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_authors')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_authors_last_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_first_name'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
