"""Added field: read_only for book

Revision ID: bd38e9b43bfc
Revises: a3647e4eac0d
Create Date: 2024-02-05 12:04:28.586458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd38e9b43bfc'
down_revision: Union[str, None] = 'a3647e4eac0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('read_only', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'read_only')
    # ### end Alembic commands ###
